### ISSUE TITLE
Binder Error: Catalog "physionet-data" does not exist!

### ISSUE THREAD

**Issue by knutj** [SphtKr/MIMICExtractEasy#3]
When I run this command  python3 import_duckdb.py ${MIMIC_DATA_DIR} ${DATA_DIR}/mimic3.db --skip-tables --make-concepts

I geet these errors 

python3 import_duckdb.py ${MIMIC_DATA_DIR} ${DATA_DIR}/mimic3.db --skip-tables --make-concepts
Connected to duckdb...
Creating tables...
Loading data...
duckdb connection is closed
Creating views...
re.compile('"physionet-data\\.mimiciii_\\w+\\.')
/* create a table which has fuzzy boundaries on hospital admission */ /* involves first creating a lag/lead version of disch/admit time */
WITH h AS (
  SELECT
    subject_id,
    hadm_id,
    admittime,
    dischtime,
    LAG(dischtime) OVER (PARTITION BY subject_id ORDER BY admittime NULLS FIRST) AS dischtime_lag,
    LEAD(admittime) OVER (PARTITION BY subject_id ORDER BY admittime NULLS FIRST) AS admittime_lead
  FROM "physionet-data"."mimiciii_clinical"."admissions"
), adm AS (
  SELECT
    h.subject_id,
    h.hadm_id, /* this rule is: */ /*  if there are two hospitalizations within 24 hours, set the start/stop */ /*  time as half way between the two admissions */
    CASE
      WHEN NOT h.dischtime_lag IS NULL
      AND h.dischtime_lag > (
        h.admittime - INTERVAL '24' HOUR
      )
      THEN h.admittime - INTERVAL (TRY_CAST(DATE_DIFF('microseconds', h.dischtime_lag, h.admittime)/1000000.0 / 2 AS BIGINT)) SECOND
      ELSE h.admittime - INTERVAL '12' HOUR
    END AS data_start,
    CASE
      WHEN NOT h.admittime_lead IS NULL
      AND h.admittime_lead < (
        DATEADD(hour, '24', h.dischtime)
      )
      THEN DATEADD(second, TRY_CAST(DATETIME_DIFF(h.admittime_lead, h.dischtime, SECOND) / 2 AS BIGINT), h.dischtime)
      ELSE (
        DATEADD(hour, '12', h.dischtime)
      )
    END AS data_end
  FROM h
), t1 /* get first/last heart rate measurement during hospitalization for each ICUSTAY_ID */ AS (
  SELECT
    ce.icustay_id,
    MIN(charttime) AS intime_hr,
    MAX(charttime) AS outtime_hr
  FROM "physionet-data"."mimiciii_clinical"."chartevents" AS ce
  /* very loose join to admissions to ensure charttime is near patient admission */
  INNER JOIN adm
    ON ce.hadm_id = adm.hadm_id
    AND ce.charttime >= adm.data_start
    AND ce.charttime < adm.data_end
  /* only look at heart rate */
  WHERE
    ce.itemid IN (211, 220045)
  GROUP BY
    ce.icustay_id
)
/* add in subject_id/hadm_id */
SELECT
  ie.subject_id,
  ie.hadm_id,
  ie.icustay_id,
  t1.intime_hr,
  t1.outtime_hr
FROM "physionet-data"."mimiciii_clinical"."icustays" AS ie
LEFT JOIN t1
  ON ie.icustay_id = t1.icustay_id
ORDER BY
  ie.subject_id NULLS FIRST,
  ie.hadm_id NULLS FIRST,
  ie.icustay_id NULLS FIRST
Failed to execute translated SQL:  Binder Error: Catalog "physionet-data" does not exist!
duckdb connection is closed
Traceback (most recent call last):
  File "import_duckdb.py", line 408, in <module>
    sys.exit(main())
  File "import_duckdb.py", line 401, in main
    raise error
  File "import_duckdb.py", line 397, in main
    _make_duckdb_query_bigquery(key, qpath, connection, schema=schema_name)
  File "import_duckdb.py", line 222, in _make_duckdb_query_bigquery
    raise e
  File "import_duckdb.py", line 218, in _make_duckdb_query_bigquery
    conn.execute(f"CREATE VIEW {qname} AS " + sql)
duckdb.duckdb.BinderException: Binder Error: Catalog "physionet-data" does not exist!

**Comment by jocelyn2002** [comment]
Hello, have you solved this problem?
